#!/bin/sh

edit() {
  echo "Modifying $2"
  sed --in-place=.aether.bak "$1" $2
}

restart() {
  /etc/init.d/$1 restart 2> /dev/null
}

# set hostname in places
echo "Setting up hostname"
edit 's/^\(supersede host-name "\)\w*\(";\)$/\1'$HOST'\2/' \
  /etc/dhcp3/dhclient.conf

edit 's/^\(host_name \).*$/\1'$HOST.$DOMAIN'/' \
  /etc/munin/munin-node.conf

hostname $HOST

restart networking
restart munin-node
