#!/bin/sh

# add permission in NFS exports on cache server
echo "Checking for NFS permission"
$ssh_remote@cache1 "grep -q '^/var/lib/drupal $HOST(' /etc/exports"

if [[ $? -gt 0 ]]; then
  echo "Giving permission to $HOST"
  cat <<-export | $ssh_remote@cache1 'cat >> /etc/exports'
/var/lib/drupal $HOST(fsid=0,sync,no_wdelay,rw,insecure,no_subtree_check)
export
  $ssh_remote@cache1 '/etc/init.d/nfs-kernel-server reload'
else
  echo "Host $HOST already has permission"
fi

# start monitoring
echo "Checking for munin configuration"
$ssh_remote@logger "grep -q 'address $HOST\$' /etc/munin/munin.conf"

if [[ $? -gt 0 ]]; then
  echo "Adding munin configuration"
  cat <<-export | $ssh_remote@logger 'cat >> /etc/munin/munin.conf'
[aether-$ROLE;$HOST.$DOMAIN]
  address $HOST
export
else
  echo "Already exists"
fi
